language: java
jdk: openjdk11
env:
  global:
    secure: ZeBJz5NHikidayurQTesRAEuvZM9WYLe3XEtfYql62aK4fBfr8kWC6jTIahcRNvTahPYyzQ37LnW1GgEG+guaXNtbak8bQ3mDDIgVzwPSjfFXEQNcB0FqjhbyP2VcBwdDLCjKLx+gaSx8GV7rX6H6lJSJaXhZOfZ0iTpuaaPMDs4DWenNmbiWUwVahWaLii9C8pQbhg3mx6cQIVEKCyW5Da9xBdYbN35uUxWQNf8z3fiOFGpq93qmFOt4sXCDC/F55SKhnK7Waq4lmGJdaoyv817I/KNojqtAuKdM17eFnPC7t9OIlflhp15kJIUodhVuz59Ig6EuFowlNrEvseqD5tjlF1yH0rWzx1VnXKSUZnhQSxpemenZSmCtKVYInAXNzf5pmmo63Zxhxfmyzc1Vp2I8u0DywRJP2dGFp+s8sH32NLZuCEeKB8WyBwonnNw02lUDXUqKJ71nhrEvGi36AlZIclpTcgwPPHS6odFtCsgJyKWFX67tfA6WJxGftZJz349QYttT9cG+/xLnY05Kf3TEc23ttj7wF5aqup3LWV++0t3jKpn52Pfeg7ptEKlIaqlYlXyGaIhf7BOBmrfxz/q0N4vh66mrTNwgR3gyv20gDbB/S27eb8F8CZObZUnb7K57TTVx+eW8S70hDf774cHv1BLZpd6IIIfYJ1o0No=
install: true
script:
  - ./mvnw
  - ./target/*.jar
